[project]
name = "musik-cloudflare"
version = "0.1.0"
description = "Cloudflare worker for musik"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "webtypy>=0.1.7",
]

[dependency-groups]
dev = [
    "workers-py"
]
